stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - data/external/fraudTrain.csv
      - data/external/fraudTest.csv
    outs:
      - data/raw/train.csv
      - data/raw/test.csv
      
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/interim/train_cleaned.csv
      - data/interim/test_cleaned.csv