apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fraudguard-recording-rules
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: fraudguard-latency
      rules:
        - record: fraud_latency_p95
          expr: |
            histogram_quantile(
              0.95,
              sum by (le, namespace, pod) (
                rate(
                  fraud_inference_latency_seconds_bucket{namespace="fraudguard"}[5m]
                )
              )
            )
