apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fraudguard-fastapi-hpa
  namespace: fraudguard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fraudguard-fastapi
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: fraud_latency_p95
      target:
        type: AverageValue
        averageValue: "500m"   # 0.5 seconds
