apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fraudguard-recording-rules
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: fraudguard-latency
      rules:
        - record: fraud_latency_p95
          expr: |
            histogram_quantile(
              0.95,
              sum by (le, namespace, pod) (
                rate(
                  fraud_model_inference_latency_seconds_bucket{namespace="fraudguard"}[5m]
                )
              )
            )
        - record: fraud_latency_p99
          expr: |
            histogram_quantile(
              0.99,
              sum by (le, namespace, pod) (
                rate(
                  fraud_model_inference_latency_seconds_bucket{namespace="fraudguard"}[5m]
                )
              )
            )


        - record: fraudguard:app_latency_p95
          expr: |
            histogram_quantile(
              0.95,
              sum by (le, namespace, pod) (
                rate(
                  http_request_latency_seconds_bucket{
                    namespace="fraudguard",
                    path="/predict"
                  }[5m]
                )
              )
            )


        - record: fraudguard:app_latency_p99
          expr: |
            histogram_quantile(
              0.99,
              sum by (le, namespace, pod) (
                rate(
                  http_request_latency_seconds_bucket{
                    namespace="fraudguard",
                    path="/predict"
                  }[5m]
                )
              )
            )

    - name: fraudguard-model-metrics
      rules:

        - record: fraudguard:fraud_rate
          expr: |
            sum(rate(fraud_positive_predictions_total[5m]))
            /
            (sum(rate(fraud_predictions_total[5m])) + 1e-10)


        - record: fraudguard:request_rate
          expr: |
            sum(rate(http_requests_total{namespace="fraudguard", path="/predict"}[1m]))
