apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fraudguard-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: fraudguard-operational
    rules:

    - alert: FraudGuardHighLatency
      expr: fraud_latency_p95 > 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High p95 latency detected"
        description: "FraudGuard p95 latency > 1s for 2 minutes"

    - alert: FraudGuardFraudSpike
      expr: rate(fraud_alerts_sent_total[5m]) > 0.5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Fraud alert spike detected"
        description: "Fraud alerts > 30 per minute"

    - alert: FraudGuardNoTraffic
      expr: rate(fraud_requests_total[5m]) == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "FraudGuard has no traffic"
        description: "No incoming requests for 2 minutes"
